stages:
  - build
  - deploy

bulid:
  stage: build
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-admin springboot re_bd
  only:
    - re_bd

deploy:
  stage: deploy
  script:
    - echo "start deploy ..."
    - cd /home/www/
    - ./docker_deploy tilitili-admin 150.158.138.139 8083
  only:
    - re_bd