stages:
  - build
  - deploy

bulid:
  stage: build
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-admin springboot master
  tags:
    - tilitili
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "start deploy ..."
    - cd /home/www/
    - ./docker_deploy tilitili-admin 150.158.138.139 8083
  tags:
    - tilitili
  only:
    - master