stages:
  - build-deploy

bulid-deploy:
  stage: build-deploy
  script:
    - echo "start building tilitili-admin ..."
    - cd /home/www/
    - ./docker_build tilitili-admin 8083
  only:
    - deploy