stages:
  - build
  - deploy

bulid:
  stage: build
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-admin springboot
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "start deploy ..."
    - cd /home/www/
    - ./docker_deploy tilitili-admin 47.100.66.36 8083
  only:
    - master