stages:
  - build-deploy

bulid-deploy:
  stage: build-deploy
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-admin
    - ./docker_deploy tilitili-admin 47.100.66.36 8083
  only:
    - deploy