From openjdk:11-jre-slim-buster

COPY libAquesTalk10.so.1 /usr/lib/
COPY libAqKanji2Koe.so.4 /usr/lib/
COPY libAqUsrDic.so.4 /usr/lib/
COPY libjwoff2.so /usr/lib/

CMD ldconfig

COPY silk /home/admin/silk/

ADD target/*.jar tilitili-admin.jar

ENTRYPOINT ["java", "-jar", "-Duser.timezone=GMT+8", "tilitili-admin.jar"]