From hub.c.163.com/library/java:8-jre

COPY lib /usr/lib/

CMD ldconfig

COPY silk /home/admin/silk/

ADD target/*.jar tilitili-admin.jar

ENTRYPOINT ["java", "-jar", "-Duser.timezone=GMT+8", "tilitili-admin.jar"]