From hub.c.163.com/library/java:8-jre

ADD target/*.jar tilitili-admin.jar

COPY libAquesTalk10.so.1 /usr/lib/
COPY libAqKanji2Koe.so.4 /usr/lib/
COPY libAqUsrDic.so.4 /usr/lib/

CMD ldconfig

ENTRYPOINT ["java", "-jar", "-Duser.timezone=GMT+8", "tilitili-admin.jar"]